import type {
  SummaryData, CountryData, CategoryData, PipelineState,
  LogEntry, Document, QualityCheck
} from "./types";

export const summaryData: SummaryData = {
  totalCollected: 1847,
  jsonFileCount: 193,
  selectedActive: 240,
  selectedTarget: 300,
  verifiedCount: 187,
  verifiedRate: 77.9,
  excludedByDate: 15,
  excludedByPdf: 25,
  excludedByLang: 13,
  totalCountries: 35,
  totalOrgs: 415,
  completedDocs: 9577,
  gbExcluded: true,
  gaoExcluded: true,
};

export const countryData: CountryData[] = [
  { code: "US", name: "미국", flag: "🇺🇸", collected: 487, selected: 170, quota: 170, orgCount: 35 },
  { code: "CA", name: "캐나다", flag: "🇨🇦", collected: 89, selected: 42, quota: 45, orgCount: 12 },
  { code: "SE", name: "스웨덴", flag: "🇸🇪", collected: 67, selected: 25, quota: 25, orgCount: 11 },
  { code: "SG", name: "싱가포르", flag: "🇸🇬", collected: 58, selected: 23, quota: 25, orgCount: 9 },
  { code: "EU", name: "EU", flag: "🇪🇺", collected: 45, selected: 15, quota: 15, orgCount: 5 },
  { code: "AT", name: "오스트리아", flag: "🇦🇹", collected: 34, selected: 12, quota: 12, orgCount: 4 },
  { code: "NO", name: "노르웨이", flag: "🇳🇴", collected: 31, selected: 18, quota: 20, orgCount: 6 },
  { code: "IN", name: "인도", flag: "🇮🇳", collected: 28, selected: 10, quota: 12, orgCount: 3 },
  { code: "IT", name: "이탈리아", flag: "🇮🇹", collected: 25, selected: 15, quota: 20, orgCount: 5 },
  { code: "BE", name: "벨기에", flag: "🇧🇪", collected: 22, selected: 8, quota: 10, orgCount: 3 },
  { code: "HU", name: "헝가리", flag: "🇭🇺", collected: 15, selected: 6, quota: 8, orgCount: 2 },
  { code: "GB", name: "영국", flag: "🇬🇧", collected: 312, selected: 0, quota: 0, orgCount: 30, excluded: true },
];

export const categoryData: CategoryData[] = [
  { name: "economy", nameKr: "경제·통상", count: 68, color: "#3b82f6", icon: "💰" },
  { name: "ai_digital", nameKr: "AI·디지털", count: 52, color: "#8b5cf6", icon: "🤖" },
  { name: "climate", nameKr: "기후·에너지", count: 47, color: "#22c55e", icon: "🌿" },
  { name: "security", nameKr: "안보·외교", count: 43, color: "#ef4444", icon: "🛡️" },
  { name: "welfare", nameKr: "인구·복지", count: 35, color: "#f97316", icon: "👥" },
  { name: "health", nameKr: "보건", count: 28, color: "#ec4899", icon: "🏥" },
  { name: "education", nameKr: "교육", count: 17, color: "#06b6d4", icon: "📚" },
  { name: "housing", nameKr: "주거·도시", count: 12, color: "#f59e0b", icon: "🏙️" },
];

export const pipelineState: PipelineState = {
  currentStep: 3,
  steps: {
    1: "completed",
    2: "completed",
    3: "running",
    4: "pending",
    5: "pending",
  },
  progress: 67,
  isRunning: true,
  runId: 1,
  startedAt: "2026-03-20T10:00:00",
  finishedAt: null,
  finalStatus: "running",
  totalCollected: 2262,
  totalSelected: 230,
  totalVerified: 177,
  totalExcluded: 767,
  errorMessage: null,
  hasExcelFile: false,
};

export const logEntries: LogEntry[] = [
  { timestamp: "10:32:15", level: "success", step: "resolve_dates_v2", message: "Z00057 BEA 날짜 추출 완료 (2026-02-19)" },
  { timestamp: "10:32:14", level: "info", step: "resolve_dates_v2", message: "Z00063 FRB 처리중..." },
  { timestamp: "10:32:10", level: "success", step: "resolve_dates_v2", message: "Z00054 NIST 날짜 추출 완료 (2026-01-30)" },
  { timestamp: "10:32:08", level: "warning", step: "resolve_dates_v2", message: "Z00065 CBO 접속 실패 (403) — 차단 사이트" },
  { timestamp: "10:32:05", level: "success", step: "resolve_dates_v2", message: "Z00088 PIIE 날짜 추출 완료 (2026-03-01)" },
  { timestamp: "10:32:01", level: "error", step: "resolve_dates_v2", message: "Z00345 Hudson 타임아웃 — 60초 초과" },
  { timestamp: "10:31:58", level: "success", step: "resolve_dates_v2", message: "Z00412 CRS 날짜 추출 완료 (2026-02-28)" },
  { timestamp: "10:31:55", level: "info", step: "resolve_dates_v2", message: "진행률: 201/300 (67%)" },
  { timestamp: "10:31:50", level: "success", step: "resolve_dates_v2", message: "Z00323 RAND 날짜 추출 완료 (2026-01-15)" },
  { timestamp: "10:31:45", level: "success", step: "resolve_pdfs", message: "전체 PDF URL 추출 완료 (280/300)" },
];

const sampleDocs: Document[] = [
  {
    id: 1, country: "US", countryFlag: "🇺🇸", orgName: "Bureau of Economic Analysis", orgCode: "Z00057",
    title: "Trade Policy Implications for Supply Chain Resilience in the Indo-Pacific Region",
    docType: "보고서", publishedDate: "2026-02-19", relevanceScore: 0.85,
    status: "verified", pdfUrl: "https://www.bea.gov/report.pdf", pdfSizeKb: 1240,
    authors: "John Smith, Jane Doe", description: "This paper examines the implications of recent trade policy shifts on supply chain resilience across the Indo-Pacific region.",
    keywords: ["trade", "supply chain", "GDP", "Indo-Pacific"], category: "경제·통상",
    brmCode1: "0011", brmCode2: "0165", journal: "BEA Working Paper Series",
    volumeInfo: "Vol.2026, No.02", isbn: "978-0-16-095862-0", issn: "", license: "C",
    dateVerified: true, dateVerifiedBy: "meta_tag", pdfVerified: true, langVerified: true, excludeReasons: [],
  },
  {
    id: 2, country: "EU", countryFlag: "🇪🇺", orgName: "European Parliamentary Research Service", orgCode: "NEW_EPRS",
    title: "Education Reform and Digital Transformation: A Comparative Analysis",
    docType: "정책자료", publishedDate: "2026-03-05", relevanceScore: 0.82,
    status: "verified", pdfUrl: "https://europarl.europa.eu/report.pdf", pdfSizeKb: 890,
    authors: "Maria Garcia, Lars Andersen", description: "A comparative analysis of education reform initiatives across EU member states with focus on digital transformation strategies.",
    keywords: ["education", "digital transformation", "EU policy", "reform"], category: "교육",
    brmCode1: "0003", brmCode2: "0039", journal: "EPRS Briefing",
    volumeInfo: "Vol.2026, No.03", isbn: "", issn: "2599-9060", license: "CC BY",
    dateVerified: true, dateVerifiedBy: "json_ld", pdfVerified: true, langVerified: true, excludeReasons: [],
  },
  {
    id: 3, country: "CA", countryFlag: "🇨🇦", orgName: "Parliamentary Budget Officer", orgCode: "Z00258",
    title: "Fiscal Outlook 2026: Economic Projections and Budgetary Impact",
    docType: "보고서", publishedDate: "2026-01-20", relevanceScore: 0.78,
    status: "unverified", pdfUrl: null, pdfSizeKb: null,
    authors: "PBO Research Team", description: "The PBO's updated fiscal outlook incorporating recent economic developments and policy changes.",
    keywords: ["fiscal policy", "budget", "economic outlook", "Canada"], category: "경제·통상",
    brmCode1: "0013", brmCode2: "0187", journal: "PBO Report",
    volumeInfo: "Vol.2026, No.01", isbn: "", issn: "", license: "C",
    dateVerified: false, dateVerifiedBy: "", pdfVerified: false, langVerified: true, excludeReasons: [],
  },
  {
    id: 4, country: "SE", countryFlag: "🇸🇪", orgName: "Government Offices of Sweden", orgCode: "Z00091",
    title: "Climate Strategy for Sustainable Industrial Transition",
    docType: "정책자료", publishedDate: "2026-02-10", relevanceScore: 0.75,
    status: "verified", pdfUrl: "https://government.se/report.pdf", pdfSizeKb: 2100,
    authors: "Swedish Ministry of Climate", description: "Sweden's updated climate strategy focusing on sustainable industrial transition and carbon neutrality targets.",
    keywords: ["climate change", "carbon neutrality", "industrial policy", "sustainability"], category: "기후·에너지",
    brmCode1: "0017", brmCode2: "0221", journal: "Swedish Government Report",
    volumeInfo: "Vol.2026, No.02", isbn: "", issn: "", license: "CC BY-NC",
    dateVerified: true, dateVerifiedBy: "time_tag", pdfVerified: true, langVerified: true, excludeReasons: [],
  },
  {
    id: 5, country: "SG", countryFlag: "🇸🇬", orgName: "Monetary Authority of Singapore", orgCode: "Z00112",
    title: "Financial Stability Review: Emerging Risks in Digital Asset Markets",
    docType: "발간자료", publishedDate: "2026-01-15", relevanceScore: 0.73,
    status: "excluded", pdfUrl: "https://mas.gov.sg/report.pdf", pdfSizeKb: 45,
    authors: "MAS Financial Stability Department", description: "Assessment of emerging risks in digital asset markets and their implications for financial stability.",
    keywords: ["financial stability", "digital assets", "fintech", "risk assessment"], category: "경제·통상",
    brmCode1: "0013", brmCode2: "0187", journal: "MAS Financial Stability Review",
    volumeInfo: "Vol.2026, No.01", isbn: "", issn: "", license: "C",
    dateVerified: true, dateVerifiedBy: "meta_tag", pdfVerified: false, langVerified: true,
    excludeReasons: ["PDF 크기 미달 (45KB < 100KB)"],
  },
  {
    id: 6, country: "US", countryFlag: "🇺🇸", orgName: "Congressional Research Service", orgCode: "Z00412",
    title: "Artificial Intelligence Governance: Federal Regulatory Frameworks and International Cooperation",
    docType: "정책자료", publishedDate: "2026-02-28", relevanceScore: 0.91,
    status: "verified", pdfUrl: "https://crsreports.congress.gov/report.pdf", pdfSizeKb: 560,
    authors: "Chris Lee, Alex Wong, Patricia Kim", description: "An overview of federal regulatory frameworks for AI governance and international cooperation mechanisms.",
    keywords: ["artificial intelligence", "governance", "regulation", "international cooperation"], category: "AI·디지털",
    brmCode1: "0014", brmCode2: "0194", journal: "CRS Report",
    volumeInfo: "Vol.2026, No.02", isbn: "", issn: "", license: "Public Domain",
    dateVerified: true, dateVerifiedBy: "meta_tag", pdfVerified: true, langVerified: true, excludeReasons: [],
  },
  {
    id: 7, country: "NO", countryFlag: "🇳🇴", orgName: "Norwegian Agency for Development", orgCode: "Z00001",
    title: "Global Health Security and Pandemic Preparedness: Lessons from Nordic Countries",
    docType: "보고서", publishedDate: "2026-03-10", relevanceScore: 0.70,
    status: "verified", pdfUrl: "https://norad.no/report.pdf", pdfSizeKb: 780,
    authors: "Nordic Health Research Group", description: "Analysis of pandemic preparedness strategies across Nordic countries with recommendations for global health security.",
    keywords: ["public health", "pandemic", "health security", "Nordic"], category: "보건",
    brmCode1: "0009", brmCode2: "0125", journal: "Norad Publication",
    volumeInfo: "Vol.2026, No.03", isbn: "", issn: "", license: "CC BY",
    dateVerified: true, dateVerifiedBy: "json_ld", pdfVerified: true, langVerified: true, excludeReasons: [],
  },
  {
    id: 8, country: "AT", countryFlag: "🇦🇹", orgName: "Austrian Institute of Economic Research", orgCode: "Z00250",
    title: "Housing Market Dynamics and Urban Planning Challenges in Central Europe",
    docType: "발간자료", publishedDate: "2026-01-25", relevanceScore: 0.68,
    status: "verified", pdfUrl: "https://wifo.ac.at/report.pdf", pdfSizeKb: 430,
    authors: "WIFO Research Team", description: "Examination of housing market trends and urban planning challenges faced by Central European economies.",
    keywords: ["housing policy", "urban planning", "real estate", "Central Europe"], category: "주거·도시",
    brmCode1: "0006", brmCode2: "0070", journal: "WIFO Working Paper",
    volumeInfo: "Vol.2026, No.01", isbn: "", issn: "1605-7128", license: "C",
    dateVerified: true, dateVerifiedBy: "css_selector", pdfVerified: true, langVerified: true, excludeReasons: [],
  },
];

export const documents: Document[] = sampleDocs;

export const qualityChecks: QualityCheck[] = [
  { label: "발행연도 2026+", passed: true, detail: "187/187건 통과" },
  { label: "PDF 유효 (Content-Type + 100KB+)", passed: false, detail: "162/187건 통과 (25건 미달)" },
  { label: "영어 문서만", passed: true, detail: "187/187건 통과" },
  { label: "키워드 3개+", passed: true, detail: "240/240건 통과" },
  { label: "카테고리 3개+ 분야", passed: true, detail: "8/8 카테고리 충족" },
  { label: "국가 10개+", passed: true, detail: "현재 11개국" },
  { label: "기관 35개+", passed: true, detail: "현재 48개 기관" },
  { label: "기관당 10% 이하", passed: true, detail: "최대 기관: RAND (7.1%)" },
  { label: "GB/UK 미포함", passed: true, detail: "GB 문서 0건" },
  { label: "중복 0건", passed: true, detail: "제목 중복 0건" },
  { label: "제목 15자 이상", passed: true, detail: "240/240건 통과" },
  { label: "기수집 미중복", passed: true, detail: "9,577건 대조 완료" },
];
